argoCDNamespace: argo-gitops
helmChartName: argo-cluster-upgrade
namespaceDestination: argo-cluster-upgrade
repoURL: ssh://git@odyssey.rowini.net:7999/ocp/helm-chart-cluster-upgrade.git

generatorsList:
- clusters:
    selector:
      matchLabels:
        ocp.csg.com/argocd-state: "staging"
      matchExpressions:
        - key: ocp.csg.com/domain
          operator: In
          values:
          - 'openshift4-app1-uh1-dtbasic-i.caas.hedani.net'
    values:
      track: OCP410.46
- clusters:
    selector:
      matchLabels:
        ocp.csg.com/argocd-state: 'staging'
      matchExpressions:
        - key: ocp.csg.com/datacenter
          operator: In
          values: ['UH1', 'PRI', 'SLO', 'SIP']
        - key:  ocp.csg.com/cluster-type
          operator: NotIn
          values: ['Ephemeral']
    values:
      track: TRACK1
- clusters:
    selector:
      matchLabels:
        ocp.csg.com/argocd-state: 'staging'
      matchExpressions:
        - key: ocp.csg.com/datacenter
          operator: In
          values: ['N18', 'CDC', 'GSH', 'JUR']
        - key:  ocp.csg.com/cluster-type
          operator: NotIn
          values: ['Ephemeral']
    values:
      track: TRACK2
###############################################################################################################################
###############################################################################################################################
# Helm chart values
###############################################################################################################################
###############################################################################################################################
valuesList:
  values: |-
    targetRevision: '{{ values.track }}-{{metadata.labels.ocp.csg.com/environment}}'

syncPolicyList:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
  - ApplyOutOfSyncOnly=true
  - CreateNamespace=true
  - PruneLast=true
