---
- name: Ensure manifest directory exists
  file:
    path: "{{ role_path }}/files/{{ namespace }}"
    state: directory

- name: Copy generated manifest into namespace-specific files directory
  copy:
    src: "{{ manifest_output_path }}"
    dest: "{{ role_path }}/files/{{ namespace }}/egressip.yaml"
  when: manifest_output_path is defined

# ------------------------------
#  GitLab MR Creation
# ------------------------------
- name: Create a new branch in GitLab
  uri:
    url: "{{ lookup('env','CI_API_V4_URL') }}/projects/{{ gitlab_project_id }}/repository/branches"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    body_format: json
    body:
      branch: "egress-manifest-{{ lookup('env','CI_JOB_ID') }}"
      ref: "{{ lookup('env','CI_COMMIT_REF_NAME') }}"
    status_code: [201, 400]  # 201 if created, 400 if already exists
  register: branch_result

- name: Commit manifest file to branch
  uri:
    url: "{{ lookup('env','CI_API_V4_URL') }}/projects/{{ gitlab_project_id }}/repository/commits"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    body_format: json
    body:
      branch: "egress-manifest-{{ lookup('env','CI_JOB_ID') }}"
      commit_message: "Add egress manifest for namespace {{ namespace }}"
      actions:
        - action: "create"
          file_path: "roles/egress/files/{{ namespace }}/egressip.yaml"
          content: "{{ lookup('file', role_path ~ '/files/' ~ namespace ~ '/egressip.yaml') }}"
    status_code: 201

- name: Create Merge Request
  uri:
    url: "{{ lookup('env','CI_API_V4_URL') }}/projects/{{ gitlab_project_id }}/merge_requests"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    body_format: json
    body:
      source_branch: "egress-manifest-{{ lookup('env','CI_JOB_ID') }}"
      target_branch: "{{ lookup('env','CI_COMMIT_REF_NAME') }}"
      title: "Add EgressIP manifest for {{ namespace }}"
      description: |
        This MR contains the egress manifest for namespace **{{ namespace }}**.

        Auto-generated by Ansible during CI job {{ lookup('env','CI_JOB_ID') }}.
    status_code: 201
  register: mr_result

- name: Show MR URL
  debug:
    msg: "Merge Request created: {{ mr_result.json.web_url }}"

