---
- name: Apply cert-manager manifests
  k8s:
    definition: "{{ lookup('file', item) | from_yaml }}"
  loop: "{{ query('fileglob', '*.yml') | sort }}"

- name: Install cert-manager deployment
  k8s:
    definition: "{{ lookup('template', 'templates/cert-manager.yml.j2') | from_yaml }}"
  when: lookup('k8s', api_version='apps/v1', kind='Deployment', resource_name='cert-manager', namespace='cert-manager') | length <= 0

- name: Wait for the cert-manager deployments to rollout
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ item }}"
    namespace: cert-manager
  register: _cert_manager_deployment_info
  vars:
    query: "resources[0].status.readyReplicas == resources[0].status.replicas"
  until: _cert_manager_deployment_info | json_query(query)
  retries: 90
  delay: 15
  loop:
    - cert-manager
    - cert-manager-cainjector
    - cert-manager-webhook
